bridges = []

[[instances]]
name = "Junto Holochain Test"
id = "junto-holochain-test"
dna_hash = "QmSoKQgdvpXkvA5Wc2iXrzTVgnpqcs2uz6dATXtqxHhZ1M"
uri = "file:./dna/basic-chat.dna.json"

[[UIs]]
name = "Junto Test UI"
id = "junto-test-ui"
uri = "file:./ui.zip"

[[UIs.instance_references]]
ui_handle = "junto-test-ui"
instance_id = "junto-test-ui"